services:
  backend:
    user: root
    build:
      context: .docker/backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www
    tty: true

  frontend:
    user: root
    build:
      context: .docker/frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/var/www
    tty: true

  database:
    image: postgres:16.3-alpine3.20
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
